CREATE DATABASE gymtracker;
CREATE TABLE exercises (
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name VARCHAR(50) NOT NULL UNIQUE,
	muscle_group VARCHAR(50) NOT NULL,
	description VARCHAR(50),
	date_creation TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

